version: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: unless-stopped

  app:
    image: nextcloud
    depends_on:
      - db
      - redis
    volumes:
      - nextcloud:/var/www/html
    restart: unless-stopped
    environment:
      # nginx proxy
      MYSQL_HOST: db
      REDIS_HOST: redis
      VIRTUAL_HOST: $HOST
      LETSENCRYPT_HOST: $HOST
      LETSENCRYPT_EMAIL: $EMAIL
    env_file:
      - db.env
    networks:
      - proxy
      - default

volumes:
  nextcloud:
  db:

networks:
  proxy:
    external:
      name: nginx-proxy
