version: '3'
services:
  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: pyouroboros/ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=43200 # Überprüft alle 12 Stunden - Angabe in Sekunden
      - LOG_LEVEL=error
      - SELF_UPDATE=true
        #- IGNORE=mongo influxdb postgres mariadb
      - TZ=Europe/Berlin
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
