version: '3.5'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    environment:
      - ENABLE_IPV6=true
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - './data/nginx-proxy-certs:/etc/nginx/certs:ro'
      - 'nginx-config:/etc/nginx/conf.d'
      - 'nginx-vhosts:/etc/nginx/vhost.d'
      - 'nginx-webroot:/usr/share/nginx/html'

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: unless-stopped
    volumes:
      - './data/nginx-proxy-certs:/etc/nginx/certs'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - 'nginx-config:/etc/nginx/conf.d'
      - 'nginx-vhosts:/etc/nginx/vhost.d'
      - 'nginx-webroot:/usr/share/nginx/html'

volumes:
  nginx-config:
  nginx-vhosts:
  nginx-webroot:

networks:
  default:
    name: nginx-proxy
